# Configuration for the default Kabanero stack hub
name: Kabanero Stack Hub
description: This is the default stack hub for Kabanero
version: 0.6.5
stacks:
  - name: kabanero-stack-hub
    repos:
      - url: https://github.com/kabanero-io/collections/releases/download/0.6.5/java-openliberty-0.2.3-index.yaml
      - url: https://github.com/kabanero-io/collections/releases/download/0.6.5/java-spring-boot2-0.3.28-index.yaml
      - url: https://github.com/kabanero-io/collections/releases/download/0.6.5/nodejs-0.3.3-index.yaml
      - url: https://github.com/kabanero-io/collections/releases/download/0.6.5/nodejs-express-0.2.10-index.yaml
      - url: https://github.com/kabanero-io/collections/releases/download/0.6.5/java-microprofile-0.2.26-index.yaml
image-org:
image-registry:
nginx-image-name:
